### ISSUE TITLE
Taskpaper "tagged" command does not print Project names

### ISSUE THREAD

**Issue by AshwinJay** [ttscoff/na_gem#1]
First, I want to thank you for building this tool. I love Taskpaper and having a command line tool for my taskpaper files is great.

I found that a few things don't work well with the `tagged` command. 

Here's a sample file:

`test.taskpaper`
```
A: @1
	- asda ads @3
	- ads asda
- ksdjopsdf @2
B:
	- asd @2
	B.1 asdad:
		- pspspspsp @2
C:
	- alsllld @3
- as l ldp @1
D (Foo bar):
	- yyrr auaasad
	- ejejej lals @2
	- asdwerw f
```

Here's what `na -f test.taskpaper tagged` prints

```
[] asda ads @3
[] ads asda
[] ksdjopsdf @2
[] asd @2
[/B.1 asdad] pspspspsp @2
[] alsllld @3
[] as l ldp @1
[] yyrr auaasad
[] ejejej lals @2
[] asdwerw f
```

Issues:
* Notice that A or B or C do not get printed in the path, but only B.1 gets printed
* I also noticed that project names with tags do not show
* Project names with parenthesis in them, like `D (Foo bar):` do not work. In this case, I changed it to `D Foo bar` and it got printed

**Comment by rhsev** [comment]
Regarding your first and second issue: if a, b and c are replaced by at least two letters, the projects are displayed. This also applies for a project with a tag.

**Comment by AshwinJay** [comment]
Ah I see. But the one with parenthesis is still an issue right?

**Comment by ttscoff** [comment]
Yes, project names cannot contain colons except at the end, and cannot 
contain parenthesis before the colon. This was mostly to avoid including 
tags in the project title, I think, it's just never come up before as an 
issue.

**Comment by ttscoff** [comment]
I just released 1.2.20 which should allow single-character projects and 
allow parenthesis before the colon. Please update your gem, test, and 
let me know.

**Comment by rhsev** [comment]
everything works as it should 👍🏻

**Comment by AshwinJay** [comment]
Thank you!
